### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by enyangxxx** [getong/mariadb-action#3]
Hello, we are making use of your GitHub Action for CI, but the 500 internal server error encountered:

"Head https://registry-1.docker.io/v2/library/docker/manifests/stable: received unexpected HTTP status: 500 Internal Server Error"

![image](https://user-images.githubusercontent.com/32799307/114044440-88ea5e80-9887-11eb-8c97-26c4863bcda9.jpeg)

Could you please look into it? Much appreciation!

**Comment by grooverdan** [comment]
Docker hub was having a glitch.
