### ISSUE TITLE
action broken since release of version 1.2

### ISSUE THREAD

**Issue by hschapitz** [getong/mariadb-action#9]
I noticed that my github actions do not work if I try to update this action to the latest version (1.2). First I thought there must a problem on my end so I tried to setup a few simple workflows but all of them are failing with an endless loop of
`Container  is still starting (current status: )`

The problem was introduced with pull request #7. While the pull requests checks are all green, the checks on the merge have failed.
* https://github.com/getong/mariadb-action/actions/runs/9562205801/job/26360504916 (ok)
* https://github.com/getong/mariadb-action/actions/runs/9563028896/job/26360671840 (failed)

This is due to the fact that pull requests check against the action from the master branch
* https://github.com/getong/mariadb-action/blob/master/.github/workflows/test.yml#L22

**Comment by getong** [comment]
Use v1.7 version, it is ok now.

Please close this issue after you test it.

**Comment by hschapitz** [comment]
@getong it seems that v1.7 does not work for me. however, v1.6 does.

v1.7 shows logs like this
`Container 884dd153046cf5189ffc1836559c3fad6d2e6236c12b0d487fa9c3d90f86f13f is still starting (current status: healthy)`

maybe we need to check for status healthy & unhealthy

**Comment by getong** [comment]
Add version v1.10, it might be ok now.

**Comment by hschapitz** [comment]
looks good. I also added #14 so the tests are running against multiple mariadb versions and it's also using the current version of the github-action
